- name: Frontend playbook1
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf